import Link from "next/link";

export default function VerifyCertificatePage({ params }: { params: { certificateId: string } }) {
  return (
    <div style={s.page}>
      <div style={s.card}>
        <div style={s.logo}>F</div>
        <h1 style={s.title}>Certificate verification</h1>
        <p style={s.sub}>This certificate ID was generated by FinanceHub.</p>
        <div style={s.idBox}>{params.certificateId}</div>
        <p style={s.note}>
          Full public verification records can be connected when certificate issuance is stored in a dedicated certificates table.
        </p>
        <Link href="/" style={s.btn}>Back to FinanceHub</Link>
      </div>
    </div>
  );
}

const s: Record<string, React.CSSProperties> = {
  page: { minHeight: "100vh", background: "#fafafa", display: "flex", alignItems: "center", justifyContent: "center", padding: 24, fontFamily: "system-ui,-apple-system,sans-serif" },
  card: { width: "100%", maxWidth: 420, background: "#fff", border: "0.5px solid #e5e5e5", borderRadius: 16, padding: "32px 28px", textAlign: "center" },
  logo: { width: 44, height: 44, borderRadius: 10, background: "#1D9E75", color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 800, margin: "0 auto 18px" },
  title: { fontSize: 22, fontWeight: 700, margin: "0 0 6px", color: "#0a0a0a" },
  sub: { fontSize: 14, color: "#666", margin: "0 0 18px" },
  idBox: { background: "#F5F5F3", border: "0.5px solid #e5e5e5", borderRadius: 10, padding: "12px", fontFamily: "ui-monospace, monospace", fontSize: 13, fontWeight: 700, color: "#0F6E56", marginBottom: 14 },
  note: { fontSize: 12, color: "#888", lineHeight: 1.6, margin: "0 0 20px" },
  btn: { display: "inline-block", padding: "10px 18px", borderRadius: 9, background: "#1D9E75", color: "#fff", textDecoration: "none", fontSize: 13, fontWeight: 600 },
};
